### ISSUE TITLE
 Error while dialing dial tcp: address ://11.167.99.43:2379: too many colons in address\""

### ISSUE THREAD

**Issue by ennian001** [api7/etcd-adapter#19]
why dashboard happend this erro?
the version of dashboard is "apisix-dashboard-3.0.1-0.el7.x86_64.rpm"
and my etcd-adapter-main project config.yaml as follows:
```
server:
  host: 0.0.0.0
  port: 2379
# tls:
#   cert: /path/to/file.pem
#   key: /path/to/file.pem

log:
  level: info

datasource:
  type: mysql # btree of mysql
  mysql:
    host: 10.167.108.188
    port: 13306
    username: root
    password: F1@admin
    database: apisix
```
